.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HOMER" "1" "April 2014" "" "Homer Manual"
.
.SH "NAME"
\fBhomer\fR \- Launch daemons
.
.SH "SYNOPSIS"
\fBhomer\fR [\fB\-q\fR] [\fB\-p\fR \fIfile\fR] [[\fB\-o\fR \fIfile\fR] [\fB\-e\fR \fIfile\fR] | \fB\-O\fR \fIfile\fR] <command>
.
.SH "DESCRIPTION"
Launch the command <command> as a daemon\. All options must be given \fIbefore\fR the command, anything given after it will be passed to the command itself\.
.
.SH "OPTIONS"
.
.TP
\fB\-e\fR \fIfile\fR
Redirect \fBstderr\fR to a file\. If it already exists, new data will be appended to its content\.
.
.TP
\fB\-h\fR
Print the help and exit
.
.TP
\fB\-o\fR \fIfile\fR
Redirect \fBstdout\fR to a file\. See also \fB\-e\fR\.
.
.TP
\fB\-O\fR \fIfile\fR
Redirect both \fBstdout\fR and \fBstderr\fR to the same file\. This is equivalent to using \fB\-e\fR and \fB\-o\fR with the same file\.
.
.TP
\fB\-p\fR \fIfile\fR
Write the PID of the daemon to a file\.
.
.TP
\fB\-q\fR
Quiet mode\. By default, a success message with the PID of the new process is printed\. This option removes it but doesn\'t suppress possible error messages\.
.
.TP
\fB\-v\fR
Print the version and exit
.
.SH "EXAMPLES"
.
.TP
Start a program with an unique log:
\fBhomer \-O myserver\.log myserver \-\-my\-option my\-arg\fR
.
.TP
Quiet mode and PID file:
\fBhomer \-q \-p mycmd\.pid \-o mycmd\.out \-e mycmd\.err mycmd\fR
.
.SH "AUTHOR"
Written by Baptiste Fontaine <\fIb@ptistefontaine\.fr\fR>\.
.
.SH "BUGS"
Bugs should be reported at \fIhttps://github\.com/bfontaine/homer/issues\fR\.
.
.SH "SEE ALSO"
The projet homepage is at \fIhttps://github\.com/bfontaine/homer\fR\.
